const players = [
 
    { name: "Samiullah Shinwari", country: "Afghanistan" },
    { name: "Isuru Udana", country: "Sri Lanka" },
    { name: "Jason Behrendorff", country: "Australia" },
    { name: "Tabraiz Shamsi", country: "South Africa" },
    { name: "Anrich Nortje", country: "South Africa" },
    { name: "Mujeeb Ur Rahman", country: "Afghanistan" },
    { name: "Gulbadin Naib", country: "Afghanistan" },
    { name: "Kemar Roach", country: "West Indies" },
    { name: "Nathan Coulter-Nile", country: "Australia" },
    { name: "Tom Curran", country: "England" },
    { name: "Avishka Fernando", country: "Sri Lanka" },
    { name: "Jeevan Mendis", country: "Sri Lanka" },
    { name: "Vijay Shankar", country: "India" },
    { name: "Shadab Khan", country: "Pakistan" },
    { name: "Adam Zampa", country: "Australia" },
    { name: "Dinesh Karthik", country: "India" },
    { name: "Alex Carey", country: "Australia" },
    { name: "Imam-ul-Haq", country: "Pakistan" },
    { name: "Marcus Stoinis", country: "Australia" },
    { name: "Fakhar Zaman", country: "Pakistan" },
    { name: "Chris Morris", country: "South Africa" },
    { name: "Kusal Perera", country: "Sri Lanka" },
    { name: "Moeen Ali", country: "England" },
    { name: "Thisara Perera", country: "Sri Lanka" },
    { name: "Lungi Ngidi", country: "South Africa" },
    { name: "Ravindra Jadeja", country: "India" },
    { name: "JP Duminy", country: "South Africa" },
    { name: "Sarfaraz Ahmed", country: "Pakistan" },
    { name: "Shikhar Dhawan", country: "India" },
    { name: "Bhuvneshwar Kumar", country: "India" },
    { name: "Shakib Al Hasan", country: "Bangladesh" },
    { name: "Trent Boult", country: "New Zealand" },
    { name: "Andre Russell", country: "West Indies" },
    { name: "Jason Holder", country: "West Indies" },
    { name: "Ben Stokes", country: "England" },
    { name: "Quinton De Kock", country: "South Africa" },
    { name: "Nicholas Pooran", country: "West Indies" },
    { name: "Pat Cummins", country: "Australia" },
    { name: "Adil Rashid", country: "England" },
    { name: "Shimron Hetmyer", country: "West Indies" },
    { name: "Faf Du Plessis", country: "South Africa" },
    { name: "Kane Williamson", country: "New Zealand" },
    { name: "Eoin Morgan", country: "England" },
    { name: "Joe Root", country: "England" },
    { name: "Angelo Mathews", country: "Sri Lanka" },
    { name: "David Warner", country: "Australia" },
    { name: "Aaron Finch", country: "Australia" },
    { name: "Mitchell Starc", country: "Australia" },
    { name: "Rashid Khan", country: "Afghanistan" },
    { name: "Jasprit Bumrah", country: "India" },
    { name: "Babar Azam", country: "Pakistan" },
    { name: "KL Rahul", country: "India" },
    { name: "Hardik Pandya", country: "India" },
    { name: "Shoaib Malik", country: "Pakistan" },
    { name: "Mohammad Hafeez", country: "Pakistan" },
    { name: "Steve Smith", country: "Australia" },
    { name: "Lasith Malinga", country: "Sri Lanka" },
    { name: "Ross Taylor", country: "New Zealand" },
    { name: "Jos Buttler", country: "England" },
    { name: "Jonny Bairstow", country: "England" },
    { name: "MS Dhoni", country: "India" },
    { name: "Rohit Sharma", country: "India" },
    { name: "Virat Kohli", country: "India" }



        ];